name: oliapro
description: "the best work"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.6+7

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  #shimmer: ^2.0.0
  #flutter_ringtone_player: ^4.0.0+3
  cupertino_icons: ^1.0.2
  avatar_glow: ^3.0.1
  get: 4.6.6
  dio: 5.5.0+1
  #2.2.2
  shared_preferences: 2.3.1
  #3.3.1
  cached_network_image: 3.4.0
  #extended_image: 8.2.3
  #3.3.1
  flutter_cache_manager: 3.4.0
  #5.9.0
  flutter_screenutil: 5.9.3
  pull_to_refresh: 2.0.0
  fluttertoast: 8.2.4
  flutter_easyloading: 3.0.5
  # 设备信息5.0.1(暂时不能升级5.0.1，和wakelock 冲突)
  #4.2.0
  package_info_plus: 8.0.1
  #9.1.1
  device_info_plus: 10.1.1
  #0.3.6
  android_id: 0.4.0
  encrypt: 5.0.3
  #3.7.4
  pointycastle: 3.9.1
  #2.3.1
  objectbox: 4.0.1
  # 2.3.1
  objectbox_flutter_libs: 4.0.1
  #0.18.1
  intl: 0.19.0
  event_bus: 2.0.0
  #6.3.0/5.3.1
  agora_rtc_engine: 6.3.2
  agora_rtm: 1.5.9
  #2.4.0
  web_socket_channel: 3.0.1
  #11.3.0
  permission_handler: 11.3.1
  notification_permissions: ^0.6.1
  flutter_rating_bar: 4.0.1
  video_player: 2.8.3
  #2.0.0 需要android 34/ 1.6.4
  emoji_picker_flutter: 1.6.4
  #1.0.7
  image_picker: 1.1.2
  carousel_slider: 5.0.0
  screen_protector: 1.4.2
  wakelock_plus: 1.2.7
  #2.1.0
  flutter_datetime_picker_plus: 2.2.0
  camera: 0.10.5+9
  camera_android_camerax: 0.5.0+33
  auto_size_text: 3.0.0
  #5.2.1
  audioplayers: 6.0.0
  #4.4.2
  webview_flutter: 4.8.0
  # 外部浏览器，open三方
  # 这个在6.1.1时，打开外部浏览器好像是打开它的一个webview，导致有个scheme问题
  #6.1.10
  url_launcher: 6.3.0
  #6.0.17
  url_launcher_android: 6.3.3
  percent_indicator: ^4.2.3
  #4.31.0
  adjust_sdk: 4.31.0
  flutter_slidable: 3.1.1
  simple_animations: 5.0.2
  sa4_migration_kit: ^1.0.0
  flutter_swiper_null_safety_flutter3: 4.0.3
  #9.2.13
  flutter_sound: 9.6.0
  #0.1.18
  audio_session: 0.1.21
  dots_indicator: 3.0.0
  date_format: 2.0.7
  #3.1.2
  animate_do: 3.3.4
  sprintf: 7.0.0
  #image_gallery_saver: 2.0.3
  flutter_vcard: 0.0.2
  gradient_borders: 1.0.1
  #borders: 0.1.0
  bot_toast: 4.1.3
  #2.2.0
  flutter_image_compress: 2.3.0
  #2.1.2
  path_provider: 2.1.4
  #3.1.0
  lottie: 3.1.2
  launch_review: ^3.0.1
  qr_flutter: ^4.1.0
  gif_view: ^0.4.4
  #sentry_flutter: ^8.3.0
  #vap_player: 0.0.6
  #win32: ^5.5.3




  language:
    path: plugins/language

  better_player:
    path: plugins/betterplayer-0.0.84

  image_gallery_saver:
    path: plugins/image_gallery_saver-master

  mypackage:
    path: plugins/mypackage

  flutter_vap2:
    path: plugins/flutter_vap2-2.0.1

  custom_navigation_bar:
    path: plugins/custom_bubble_navigation_bar-master

  cached_video_player_plus:
    path: plugins/cached_video_player_plus-main




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  objectbox_generator: 4.0.1
  build_runner: any
  pretty_dio_logger: 1.4.0


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/json/
    - assets/ring/
    - assets/final/
    - assets/match/
    - assets/lottery/
    - assets/img/
    - assets/benefit/
    - assets/anima/
    - assets/reward/
    - assets/frame/
    - assets/image/
    - assets/sign/

  fonts:
    - family: NotoSans-Regular
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
    - family: NotoSans-Bold
      fonts:
        - asset: fonts/NotoSans-Bold.ttf

